---
- name: Ensure HAProxy is installed
  become: yes
  package:
    name: "{{ haproxy_package_name }}"
    state: present

- name: configure haproxy logrotation
  become: yes
  template:
    backup: no
    dest: /etc/logrotate.d/haproxy
    src: logrotated-haproxy.j2

# TODO: This is still in development- more configuration is needed to prevent
# some haproxy logs going to the console, and to potentially take account of
# other apps using the same syslog facility (probably unlikely)
- name: configure haproxy log file
  become: yes
  template:
    backup: no
    # Deliberately named to overwrite the ubuntu haproxy config:
    dest: /etc/rsyslog.d/49-haproxy.conf
    src: rsyslogd-haproxy.j2
  when: haproxy_syslog_enable
  notify:
  - restart rsyslog

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  become: yes
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure SELinux to allow all connections
  become: yes
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  # selinux_enabled fact is set by
  # https://github.com/openmicroscopy/infrastructure/tree/master/ansible/roles/selinux-utils
  # Since this is an external role we can't assume it's been run
  when: "selinux_enabled | default(False)"

- stat: path=/etc/haproxy/crt-list.txt
  register: st

- name: Copy HAProxy crt-list.
  become: yes
  template:
    src: "crt-list.txt.j2"
    dest: /etc/haproxy/crt-list.txt
    mode: 0644
  when: not st.stat.exists

- name: Copy HAProxy configuration in place.
  become: yes
  template:
    src: "{{ haproxy_cfg_template }}"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
  register: config

- name: Ensure HAProxy is started and enabled on boot.
  become: yes
  service: name=haproxy state=started enabled=yes

# Conditional restart below because of https://github.com/ansible/ansible/issues/15476
# Restarting the HAProxy service needs to be role-scoped, to make sure follow-up roles
# such as mage-certbot get the expected machine state.
- name: Restart HAProxy.
  become: yes
  service: name=haproxy state=restarted enabled=yes
  when: config.changed

